// <auto-generated />
using System;
using Clean.Infrastructure.Data.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Clean.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CleanContext))]
    [Migration("20210817121622_teste")]
    partial class teste
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Clean.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FiscalNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = new Guid("131ae245-1d9d-4f6d-a2fa-a6267eafbd06"),
                            BirthDay = new DateTime(1986, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Diego Armando",
                            FiscalNumber = "34801267823",
                            LastName = "de Arruda Bento",
                            Name = "Diego Armando"
                        },
                        new
                        {
                            Id = new Guid("f7fa39c7-24d5-4cb7-9fcb-4e97bddf79f1"),
                            BirthDay = new DateTime(1986, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Diego Armando",
                            FiscalNumber = "34801267823",
                            LastName = "de Arruda Bento",
                            Name = "Diego Armando"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
