// <auto-generated />
using System;
using Clean.Infrastructure.Data.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Clean.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CleanContext))]
    partial class CleanContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Clean.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FiscalNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = new Guid("728a345e-a34f-40e5-8250-08c3563f5c57"),
                            BirthDay = new DateTime(1986, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Diego Armando",
                            FiscalNumber = "34801267823",
                            Gender = 1,
                            LastName = "de Arruda Bento",
                            Name = "Diego Armando"
                        },
                        new
                        {
                            Id = new Guid("706e53ee-8799-4aa7-95ed-d5af7f9b790c"),
                            BirthDay = new DateTime(1986, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Diego Armando",
                            FiscalNumber = "34801267823",
                            Gender = 1,
                            LastName = "de Arruda Bento",
                            Name = "Diego Armando"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
